---
- hosts: localhost
  tasks:
    - name: Create an Ec2 Instamce
	  ec2:
	    key_name: mylinux
		instance_type: t2.micro
		image: ami-074dc0a6f6c764218
		wait: yes
		# group: 
		count: 1
		vpc_subnet_id: subnet-01ac2edd044abb9ef
		assign_public_ip: yes
	    region: ap-south-1
		security_group: sg-0abd8b48539ddfb17
			
		