- hosts: s1
  become: true
  tasks:
    - name: Creating A Directory If Not Exit
      ansible.builtin.file:
        path: /home/ec2-user/ansible_app
        state: directory
        mode: '0755'
    - name: Creating emty file
      file:
        path: /home/ec2-user/ansible_app/sample
        state: touch
        mode: '0664'
    - name: Insert Line
      lineinfile:
        path: /home/ec2-user/ansible_app/sample
        line: 'Welcome to Ansible YML file'
        insertbefore: BOF